"""add renewed status and previous contract

Revision ID: 2e9649aaebaf
Revises: 4e6c8a48b2ce
Create Date: 2026-09-10 22:25:03.734174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9649aaebaf'
down_revision: Union[str, Sequence[str], None] = '4e6c8a48b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    "ALTER TYPE contract_status ADD VALUE IF NOT EXISTS 'RENEWED'"
    )
    op.add_column('pawn_contracts', sa.Column('previous_contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_pawn_contracts_previous_contract_id', 'pawn_contracts', 'pawn_contracts', ['previous_contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pawn_contracts_previous_contract_id', 'pawn_contracts', type_='foreignkey')
    op.drop_column('pawn_contracts', 'previous_contract_id')
    # ### end Alembic commands ###
