"""separate pawn assets from contracts

Revision ID: c7ef2fd7c876
Revises: 
Create Date: 2026-08-03 00:03:13.551169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ef2fd7c876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('pawn_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_code', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('monthly_interest_amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REDEEMED', 'OVERDUE', 'LIQUIDATED', name='contract_status'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pawn_contracts_contract_code'), 'pawn_contracts', ['contract_code'], unique=True)
    op.create_index(op.f('ix_pawn_contracts_customer_id'), 'pawn_contracts', ['customer_id'], unique=False)
    op.create_table('pawn_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['pawn_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pawn_assets_contract_id'), 'pawn_assets', ['contract_id'], unique=False)
    op.create_index(op.f('ix_pawn_assets_license_plate'), 'pawn_assets', ['license_plate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pawn_assets_license_plate'), table_name='pawn_assets')
    op.drop_index(op.f('ix_pawn_assets_contract_id'), table_name='pawn_assets')
    op.drop_table('pawn_assets')
    op.drop_index(op.f('ix_pawn_contracts_customer_id'), table_name='pawn_contracts')
    op.drop_index(op.f('ix_pawn_contracts_contract_code'), table_name='pawn_contracts')
    op.drop_table('pawn_contracts')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
