"""remove asset type and description from pawn assets

Revision ID: ebf0b7b6ae0b
Revises: 6feadf1b7fd3
Create Date: 2026-09-23 21:43:43.720757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf0b7b6ae0b'
down_revision: Union[str, Sequence[str], None] = '6feadf1b7fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pawn_assets', 'asset_type')
    op.drop_column('pawn_assets', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pawn_assets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('pawn_assets', sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
